# Generated by Django 2.0.3 on 2018-06-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='curso',
            name='bajada',
            field=models.CharField(default='', max_length=200, verbose_name='Bajada '),
        ),
        migrations.AddField(
            model_name='curso',
            name='destinatarios',
            field=models.TextField(default='', verbose_name='Destinatarios'),
        ),
        migrations.AddField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('1', 'Inicial'), ('2', 'Intermedio'), ('3', 'Avanzado')], default='1', max_length=1, verbose_name='Nivel'),
        ),
        migrations.AddField(
            model_name='curso',
            name='objetivos',
            field=models.TextField(default='', verbose_name='Objetivos'),
        ),
        migrations.AddField(
            model_name='curso',
            name='resumen',
            field=models.TextField(default='', verbose_name='Resumen'),
        ),
        migrations.AddField(
            model_name='curso',
            name='subtitulo',
            field=models.CharField(default='', max_length=200, verbose_name='Subtítulo'),
        ),
        migrations.AddField(
            model_name='curso',
            name='tipo',
            field=models.CharField(choices=[('e', 'Extensión'), ('p', 'Posgrado')], default='e', max_length=1, verbose_name='Tipo'),
        ),
    ]
