# Generated by Django 2.0.3 on 2018-06-13 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_auto_20180608_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='docente',
        ),
        migrations.AddField(
            model_name='curso',
            name='docente',
            field=models.ManyToManyField(limit_choices_to={'docente': True}, to=settings.AUTH_USER_MODEL, verbose_name='Docente/s'),
        ),
    ]
