# Generated by Django 2.0.3 on 2018-06-13 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_auto_20180613_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='docente',
        ),
        migrations.AddField(
            model_name='curso',
            name='ayudantes',
            field=models.ManyToManyField(limit_choices_to={'docente': True}, related_name='ayudantes', to=settings.AUTH_USER_MODEL, verbose_name='Ayudante/s'),
        ),
        migrations.AddField(
            model_name='curso',
            name='docentes',
            field=models.ManyToManyField(limit_choices_to={'docente': True}, related_name='docentes', to=settings.AUTH_USER_MODEL, verbose_name='Docente/s'),
        ),
    ]
