# Generated by Django 2.0.3 on 2018-04-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_auto_20180423_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='periodo',
            field=models.CharField(blank=True, editable=False, max_length=10, verbose_name='Perdiodo del Curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=20, verbose_name='Código del Curso'),
        ),
    ]
