# Generated by Django 2.0.3 on 2018-04-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_auto_20180425_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código del Curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='periodo',
            field=models.CharField(blank=True, max_length=10, verbose_name='Perdiodo del Curso'),
        ),
    ]
