# Generated by Django 2.0.3 on 2018-06-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='categorias',
            field=models.ManyToManyField(to='gestion.Categoria', verbose_name='Categorias'),
        ),
    ]
