# Generated by Django 2.0.3 on 2018-05-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_auto_20180425_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=20, verbose_name='Código del Curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='periodo',
            field=models.CharField(blank=True, editable=False, max_length=10, verbose_name='Perdiodo del Curso'),
        ),
    ]
