# Generated by Django 2.0.3 on 2018-06-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_curso_categorias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ('categoria',)},
        ),
        migrations.AlterField(
            model_name='curso',
            name='arancel',
            field=models.FloatField(default=0, verbose_name='Arancel'),
        ),
    ]
