# Generated by Django 2.0.3 on 2018-05-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_auto_20180504_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripto',
            name='pago',
            field=models.IntegerField(default=0, editable=False, verbose_name='Pagó'),
        ),
    ]
