# Generated by Django 2.0.3 on 2018-05-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_auto_20180510_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripto',
            name='pago',
            field=models.IntegerField(default=0, verbose_name='Pagó'),
        ),
    ]
