# Generated by Django 2.0.3 on 2018-06-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_auto_20180613_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='arancel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Arancel'),
        ),
    ]
