# Generated by Django 2.0.3 on 2018-06-13 20:07

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('gestion', '0008_auto_20180613_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='etiquetas',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
