# Generated by Django 2.0.3 on 2018-06-13 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_curso_etiquetas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del lugar')),
                ('direccion', models.TextField(default='', verbose_name='Dirección')),
                ('telefono', models.CharField(default='', max_length=200, verbose_name='Teléfono')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='bibliografia',
            field=models.TextField(default='', verbose_name='Bibliografía'),
        ),
        migrations.AddField(
            model_name='curso',
            name='contacto',
            field=models.TextField(default='Área Transdepartamental Artes Multimediales\n Dirección de Extensión y Bienestar Estudiantil\n Viamonte 1832. Ciudad Autónoma de Buenos Aires\n (54.11) 4811-4695\n multimedia.cursos@una.edu.ar\n', verbose_name='Datos de Contacto'),
        ),
        migrations.AddField(
            model_name='curso',
            name='datos_inscripcion',
            field=models.TextField(default='', verbose_name='Datos para la inscripción'),
        ),
        migrations.AddField(
            model_name='curso',
            name='descargable',
            field=models.FileField(blank=True, upload_to='cursos_descargables', verbose_name='Material Descargable'),
        ),
        migrations.AddField(
            model_name='curso',
            name='duracion',
            field=models.TextField(default='', verbose_name='Duración'),
        ),
        migrations.AddField(
            model_name='curso',
            name='fin_inscripcion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Inicio de Inscripción'),
        ),
        migrations.AddField(
            model_name='curso',
            name='imagen_listado',
            field=models.ImageField(blank=True, upload_to='cursos_imgs_listado', verbose_name='Imagen de listado'),
        ),
        migrations.AddField(
            model_name='curso',
            name='imagenes_listado',
            field=models.FileField(blank=True, upload_to='cursos_imgs_galeria', verbose_name='Imágenes para Galería'),
        ),
        migrations.AddField(
            model_name='curso',
            name='info_inscripcion',
            field=models.TextField(default='', verbose_name='Información para la inscripción'),
        ),
        migrations.AddField(
            model_name='curso',
            name='inicio_inscripcion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Inicio de Inscripción'),
        ),
        migrations.AddField(
            model_name='curso',
            name='links',
            field=models.TextField(default='', verbose_name='Links externos / internos'),
        ),
        migrations.AddField(
            model_name='curso',
            name='programa',
            field=models.TextField(default='', verbose_name='Programa '),
        ),
        migrations.AddField(
            model_name='curso',
            name='requerimientos',
            field=models.TextField(default='', verbose_name='Requerimientos para cursar'),
        ),
        migrations.AddField(
            model_name='curso',
            name='unidad_academica',
            field=models.CharField(default='Area Transdepartamental de Artes Multimediales', max_length=200, verbose_name='Unidad Académica'),
        ),
        migrations.AddField(
            model_name='curso',
            name='videos',
            field=models.TextField(default='', verbose_name='Videos (links)'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='cursos_imgs', verbose_name='Imagen Principal'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='requisitos',
            field=models.TextField(default='', verbose_name='Requisitos de Inscripción'),
        ),
    ]
