# Generated by Django 2.0.3 on 2018-06-13 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_auto_20180613_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='fin_inscripcion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fin de Inscripción'),
        ),
    ]
