# Generated by Django 2.0.3 on 2018-06-13 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_auto_20180613_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='lugar',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='gestion.Lugar', verbose_name='Lugar de Dictado'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='contacto',
            field=models.TextField(default='Área Transdepartamental Artes Multimediales\nDirección de Extensión y Bienestar Estudiantil\nViamonte 1832. Ciudad Autónoma de Buenos Aires\n(54.11) 4811-4695\nmultimedia.cursos@una.edu.ar\n', verbose_name='Datos de Contacto'),
        ),
    ]
