# Generated by Django 2.0.3 on 2018-06-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_auto_20180613_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='imagenes_listado',
            new_name='imagenes_galeria',
        ),
        migrations.AlterField(
            model_name='curso',
            name='duracion',
            field=models.CharField(default='', max_length=200, verbose_name='Duración'),
        ),
    ]
