# Generated by Django 2.0.3 on 2018-06-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_auto_20180615_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='programa',
            field=models.TextField(default='', verbose_name='Programa'),
        ),
    ]
