# Generated by Django 2.0.3 on 2018-06-26 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_auto_20180615_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='ayudantes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'docente': True}, related_name='ayudantes', to=settings.AUTH_USER_MODEL, verbose_name='Ayudante/s'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='bajada',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Bajada '),
        ),
        migrations.AlterField(
            model_name='curso',
            name='bibliografia',
            field=models.TextField(blank=True, default='', verbose_name='Bibliografía'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='categorias',
            field=models.ManyToManyField(blank=True, to='gestion.Categoria', verbose_name='Categorias'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='contacto',
            field=models.TextField(blank=True, default='Área Transdepartamental Artes Multimediales\nDirección de Extensión y Bienestar Estudiantil\nViamonte 1832. Ciudad Autónoma de Buenos Aires\n(54.11) 4811-4695\nmultimedia.cursos@una.edu.ar\n', verbose_name='Datos de Contacto'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='datos_inscripcion',
            field=models.TextField(blank=True, default='', verbose_name='Datos para la inscripción'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='destinatarios',
            field=models.TextField(blank=True, default='', verbose_name='Destinatarios'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='etiquetas',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Etiquetas'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='info_inscripcion',
            field=models.TextField(blank=True, default='', verbose_name='Información para la inscripción'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='links',
            field=models.TextField(blank=True, default='', verbose_name='Links externos / internos'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='lugar',
            field=models.ForeignKey(blank=True, default='0', on_delete=django.db.models.deletion.CASCADE, to='gestion.Lugar', verbose_name='Lugar de Dictado'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(blank=True, choices=[('1', 'Inicial'), ('2', 'Intermedio'), ('3', 'Avanzado')], default='1', max_length=1, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='requerimientos',
            field=models.TextField(blank=True, default='', verbose_name='Requerimientos para cursar'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='requisitos',
            field=models.TextField(blank=True, default='', verbose_name='Requisitos de Inscripción'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='subtitulo',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='tipo',
            field=models.CharField(blank=True, choices=[('e', 'Extensión'), ('p', 'Posgrado')], default='e', max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='unidad_academica',
            field=models.CharField(blank=True, default='Area Transdepartamental de Artes Multimediales', max_length=200, verbose_name='Unidad Académica'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='videos',
            field=models.TextField(blank=True, default='', verbose_name='Videos (links)'),
        ),
    ]
