# Generated by Django 2.0.3 on 2018-04-04 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dias',
            name='curso',
        ),
        migrations.DeleteModel(
            name='Dias',
        ),
    ]
