# Generated by Django 2.0.3 on 2018-04-05 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0003_curso_docente'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='descripcion',
            field=models.CharField(default=0, max_length=600),
        ),
        migrations.AddField(
            model_name='curso',
            name='dias_dictado',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'docentes'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
