# Generated by Django 2.0.3 on 2018-04-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0008_auto_20180405_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='choices',
            field=models.ManyToManyField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], to='gestor.Choices'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.CharField(default='', max_length=600),
        ),
    ]
