# Generated by Django 2.0.3 on 2018-04-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0009_auto_20180405_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='choices',
            field=models.ManyToManyField(to='gestor.Choices'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='dias_dictado',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=7),
        ),
    ]
