# Generated by Django 2.0.3 on 2018-04-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0010_auto_20180405_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='dias_dictado',
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(default='', max_length=600),
        ),
        migrations.DeleteModel(
            name='Choices',
        ),
    ]
