# Generated by Django 2.0.3 on 2018-04-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0011_auto_20180405_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.CharField(default='', max_length=600),
        ),
    ]
