# Generated by Django 2.0.3 on 2018-04-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0012_auto_20180405_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(default=''),
        ),
    ]
