# Generated by Django 2.0.3 on 2018-04-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0013_auto_20180405_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='Dias',
            field=models.ManyToManyField(to='gestor.Dia'),
        ),
    ]
