# Generated by Django 2.0.3 on 2018-04-05 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0014_auto_20180405_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='Dias',
        ),
    ]
