# Generated by Django 2.0.3 on 2018-04-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0015_auto_20180405_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='dias',
            field=models.ManyToManyField(to='gestor.Dia'),
        ),
    ]
