# Generated by Django 2.0.3 on 2018-04-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0016_curso_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='dia',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
