# Generated by Django 2.0.3 on 2018-04-05 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0017_dia_orden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dia',
            options={'ordering': ('orden',)},
        ),
    ]
