# Generated by Django 2.0.3 on 2018-04-05 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0018_auto_20180405_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dia',
            options={'ordering': ('pk',)},
        ),
        migrations.RemoveField(
            model_name='dia',
            name='orden',
        ),
    ]
