# Generated by Django 2.0.3 on 2018-04-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0019_auto_20180405_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='dias',
            field=models.ManyToManyField(related_name='dias_de_dictado', to='gestor.Dia'),
        ),
    ]
