# Generated by Django 2.0.3 on 2018-04-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0020_auto_20180405_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='creacion_fecha',
            field=models.DateTimeField(verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='dias',
            field=models.ManyToManyField(to='gestor.Dia'),
        ),
    ]
