# Generated by Django 2.0.3 on 2018-04-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0021_auto_20180405_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(default='', verbose_name='Descripción'),
        ),
    ]
