# Generated by Django 2.0.3 on 2018-04-05 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0024_auto_20180405_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'docentes'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Docente'),
        ),
    ]
