# Generated by Django 2.0.3 on 2018-04-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0026_auto_20180405_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='dias',
            field=models.ManyToManyField(to='gestor.Dia', verbose_name='Días de Dictado'),
        ),
    ]
