# Generated by Django 2.0.3 on 2018-04-05 23:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0027_auto_20180405_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='creacion_fecha',
        ),
        migrations.AddField(
            model_name='curso',
            name='finalizacion_hora',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de Finalizaición'),
        ),
        migrations.AddField(
            model_name='curso',
            name='inicio_fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio'),
        ),
        migrations.AddField(
            model_name='curso',
            name='inicio_hora',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de Inicio'),
        ),
    ]
