# Generated by Django 2.0.3 on 2018-04-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0028_auto_20180405_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='costo',
            field=models.IntegerField(default=0, verbose_name='Costo'),
        ),
        migrations.AddField(
            model_name='curso',
            name='modalidad',
            field=models.CharField(choices=[('v', 'Virtual'), ('p', 'Presencial')], default='p', max_length=1, verbose_name='Modalidad'),
        ),
        migrations.AddField(
            model_name='curso',
            name='requisitos',
            field=models.TextField(default='', verbose_name='Requisitos'),
        ),
    ]
