# Generated by Django 2.0.3 on 2018-04-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0033_auto_20180405_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(default=1, upload_to='cursos_img', verbose_name='Imagen del Curso'),
        ),
    ]
