# Generated by Django 2.0.3 on 2018-04-09 18:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0034_auto_20180405_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=200, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=200, verbose_name='D.N.I.')),
                ('domicilio', models.CharField(max_length=200, verbose_name='Domicilio')),
                ('correo', models.CharField(max_length=200, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=200, verbose_name='Numero Telefónico')),
                ('alumno_una', models.BooleanField(default=0, verbose_name='¿Es alumno de la U.N.A.?')),
                ('enterado', models.CharField(max_length=200, verbose_name='¿Como se enteró del curso?')),
                ('subscripcion', models.BooleanField(default=1, verbose_name='¿Desea recibir novedades?')),
                ('pago', models.IntegerField(default=0, verbose_name='Pagó')),
                ('inscripcion_fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inscripción')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Curso', verbose_name='Curso al que se inscribe')),
            ],
        ),
    ]
