# Generated by Django 2.0.3 on 2018-04-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0036_auto_20180409_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripto',
            name='enterado',
            field=models.CharField(choices=[('redes_sociales', 'Redes Sociales (Facebook, Twitter, otra)'), ('mail', 'Newsletter/mailing'), ('cartelera', 'Cartelera de la universidad'), ('amigo', 'Recomendado por un amigo'), ('otro', 'Otros')], max_length=1, verbose_name='¿Como se enteró del curso?'),
        ),
    ]
