# Generated by Django 2.0.3 on 2018-04-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0037_auto_20180409_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripto',
            name='alumno_una',
            field=models.CharField(choices=[('no', 'No soy alumno de la UNA'), ('multimedia', 'Licenciatura en Artes Multimediales'), ('actuacion', 'Licenciatura en Actuación'), ('audiovisuales', 'Licenciatura en Artes Audiovisuales'), ('musica', 'Licenciatura en Artes Musicales'), ('visuales', 'Licenciatura en Artes Visuales'), ('movimiento', 'Licenciatura en Composición Coreográfica'), ('restauracion', 'Licenciatura en Conservación y Restauración de Bienes Culturales'), ('critica', 'Licenciatura en Crítica de Artes'), ('curaduria', 'Licenciatura en Curaduría en Artes'), ('teatro', 'Licenciatura en Dirección Escénica'), ('iluminacion', 'Licenciatura en Diseño de Iluminación de Espectáculos'), ('escenografia', 'Licenciatura en Escenografía'), ('folclore', 'Licenciatura en Folklore'), ('profesorado', 'Profesorado de Arte')], default='no', max_length=50, verbose_name='¿Como se enteró del curso?'),
        ),
        migrations.AlterField(
            model_name='inscripto',
            name='enterado',
            field=models.CharField(choices=[('redes_sociales', 'Redes Sociales (Facebook, Twitter, otra)'), ('mail', 'Newsletter/mailing'), ('cartelera', 'Cartelera de la universidad'), ('amigo', 'Recomendado por un amigo'), ('otro', 'Otros')], max_length=50, verbose_name='¿Como se enteró del curso?'),
        ),
    ]
