# Generated by Django 2.0.3 on 2018-04-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0039_auto_20180410_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='codigo',
            field=models.CharField(default='', max_length=20, verbose_name='Codigo del Curso'),
        ),
    ]
