# Generated by Django 2.0.3 on 2018-04-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0041_auto_20180412_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, verbose_name='Codigo del Curso'),
        ),
    ]
