# Generated by Django 2.0.3 on 2018-04-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0042_auto_20180412_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código del Curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='cursos_img', verbose_name='Imagen del Curso'),
        ),
    ]
